### ISSUE TITLE
Error with /fapi/v1/order - Python

### ISSUE THREAD

**Issue by olahouze** [binance-exchange/binance-signature-examples#13]
Hi

I use your code (https://github.com/binance-exchange/binance-signature-examples/blob/master/python/delivery-futures.py) and I ave 2 errors when I want to use /fapi/v1/order 

### **1. Char ? or &**
In most of case, url is XXX?timestamp={{timestamp}}&signature={{signature}}
exemple : 
- /fapi/v2/positionRisk?timestamp={{timestamp}}&signature={{signature}}
- /fapi/v2/account?timestamp={{timestamp}}&signature={{signature}}

So in your code, the "**?timestamp**" is hard code :
` url = BASE_URL + url_path + '?' + query_string + '&signature=' + hashing(query_string)`

But to use API for New Order, we must use : 
/fapi/v1/order?symbol=LTCUSDT&side=BUY&positionSide=BOTH&type=MARKET&quantity=0.087 **&** timestamp={{timestamp}}&signature={{signature}}

So it's an issue
With this URL : **https://fapi.binance.com/fapi/v1/order?symbol=LTCUSDT&side=SELL&positionSide=BOTH&type=MARKET&quantity=0.087?timestamp=1620474622959&signature=7ba203ec45bfa9c6e70a80cd8a482fa85822c5384243047d0c84c34f79cbc...**
I have this error message :
**{'code': -1102, 'msg': "Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."}**

### **2. Error with signature to past order**
I tested to change code to avoid issue with this : 
```
def send_signed_request(http_method, url_path, payload={},defaultItemTimestamp='?'):
    query_string = urlencode(payload)
    query_string = query_string.replace('%27', '%22')

    if query_string:
        query_string = "{}"+defaultItemTimestamp+"timestamp={}".format(query_string, get_timestamp())
    else:
        query_string = 'timestamp={}'.format(get_timestamp())

    url = BASE_URL + url_path + defaultItemTimestamp + query_string + '&signature=' + hashing(query_string)
    print(url)
    params = {'url': url, 'params': {}}
    response = dispatch_request(http_method)(**params)
    return response.json()
```

But now I have this error :  
**URL :** https://fapi.binance.com/fapi/v1/order?symbol=LTCUSDT&side=SELL&positionSide=BOTH&type=MARKET&quantity=0.087?timestamp=1620474622959&signature=7ba203ec45bfa9c6e70a80cd8a482fa85822c5384243047d0c84c34f79c.....
**Error message** : {'code': -1102, 'msg': "Mandatory parameter 'timestamp' was not sent, was empty/null, or malformed."}

Could you reproduce the probleme et correct its ?

Best regards

**Comment by 2pd** [comment]
1. `delivery-futures.py` only used for `/dapi/v1/order`, so I think you should look into `futures.py` file for USDT futures endpoints.
2. `timestamp` will has "?" when there is no query parameters. In the endpoint to place order,  parameters should be provided, so there will be no 2 question mark in the url, which is not correct.
3. https://github.com/binance-exchange/binance-signature-examples/blob/master/python/futures.py#L104 this file has the method already for place order,  please have a try.

**Comment by alidehghan11** [comment]
hi 
how can i use this for future https://testnet.binancefuture.com

I have two days to try, but I still can not
