### ISSUE TITLE
Error -2008, Invalid Api-Key ID. My API key is correct

### ISSUE THREAD

**Issue by smallham1** [binance-exchange/binance-signature-examples#17]
While trying to request anything that needs a signature i get this "{'code': -2008, 'msg': 'Invalid Api-Key ID.'}" or this "{"code": -2015, "msg": "Invalid API-key, IP, or permissions for action."}" error. When i request public info i do not get any errors. I know that my api key is correct because i have trouble shot it, along with the IP whitelisting feature. The api key is being used with a different wrapper with no api key errors (not at the same time). 

Here is my code:

[bintest1.txt](https://github.com/binance-exchange/binance-signature-examples/files/6588035/bintest1.txt)

This returns:
(all correct klines)
{"code": -2015, "msg": "Invalid API-key, IP, or permissions for action."}
{'code': -2008, 'msg': 'Invalid Api-Key ID.'}

Again, i know my keys are correct because i used the same ones in a different script with success. Thanks for any help in advance.

**Comment by 2pd** [comment]
if requests to `/api/v3/account` returns `{"code": -2015, "msg": "Invalid API-key, IP, or permissions for action."}`
I would suggest to check:

- if the api key and secret is correct
- id the above key/secret from production or testnet, they have different base url.
- if the api key is IP whitelisted,  is it the same ip sending to server?

**Comment by q-sag** [comment]
For those who ended up here but have this issue after trying all mentioned in above post by @2pd  try next : 
1. Regenerate API keys, and test with new one 
2. Rotate keys, until they work.

In my particular case, I rotated 7-8 keys until one of them started working. 
Not sure why this issue appears, and was surprised by solution.
