### ISSUE TITLE
APIError(code=-1022): Signature for this request is not valid.

### ISSUE THREAD

**Issue by kamlehsdatt** [binance-exchange/binance-signature-examples#18]
I have a Binance Future Order that is throwing the below error:

APIError(code=-1022): Signature for this request is not valid.

My code for the order is as below:

client.futures_create_order(
    symbol='ADAUSDT',
    side=Side,
    type='MARKET',
    quantity=trade_quantity,
    recvWindow=5000)
I can retrieve prices & a/c info with the Binance API keys but when I put the future order as above it throws an error for invalid signature. I saw solutions for this error but could not understand how to add to above order & place it.

I am not a IT person & have learned python just by google search in last week. Any help on adding the signature to the code will be appreciated, thanks a lot.

**Comment by 2pd** [comment]
the signature should be hashed by the library based on the request parameters.

May be you can try the script in this repo, it should be easier to start with.

**Comment by 2pd** [comment]
Closing this ticket as it's not related to this repo.
For API related question, please open ticket at dev.binance.vision.
