### ISSUE TITLE
Java example

### ISSUE THREAD

**Issue by tommyzat** [binance-exchange/binance-signature-examples#2]
Hello!

It would be greatly appreciated if someone could add an example for Java aswell.

Thank you!

**Comment by lesiagnapovska359** [comment]
Example on C# will be awialable?

**Comment by 2pd** [comment]
Sorry we don't have enough resources for examples in other languages.

**Comment by lesiagnapovska359** [comment]
> Sorry we don't have enough resources for examples in other languages.

Thanks for answer.

**Comment by 2pd** [comment]
But it's welcome to have PR from community for more languages.
