### ISSUE TITLE
Python code slow

### ISSUE THREAD

**Issue by tw10** [binance-exchange/binance-signature-examples#5]
Thank you so much for sharing the examples.
By comparing the python-binance package from https://github.com/sammchardy/python-binance/blob/master/binance/client.py, I find that using send_signed_request and send_public_request in the python example takes about 30% more time to run.
CPU consumption is also higher.

Do you know what could be the possible reasons?
Thanks in advance!

**Comment by 2pd** [comment]
Thanks for your feedback. Code in this repo is used for test/debug/demo, not suitable for production.
Users should be able to easily understand how signature works in python.

**Comment by tw10** [comment]
Yeah, I can see that the two follow very similar steps. That's why I can't see why there would be the difference in performance, especially considering the python-binance package offers more features and might be less efficient.
But thanks for your reply.
