### ISSUE TITLE
Binance API, Get Balance, Delphi

### ISSUE THREAD

**Issue by surinpeter** [binance-exchange/binance-signature-examples#6]
Hi, I use following code to get balances from my SPOT account on Binance. But after execution, I allways get 400 Bad request message. 

      Form1.RESTClient1.BaseURL := 'https://api.binance.com/api/v3/account';
      Form1.RESTRequest1.Params.Clear;
      Form1.RESTRequest1.METHOD := rmGet;

      aParam := Form1.RESTRequest1.Params.AddItem;
      aParam.ContentType:=ctapplication_x_www_form_urlencoded;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'X-MBX-APIKEY';
      aParam.Value := Form1.APIKEY_Binance;

      TimeStamp := Form1.UNIXTimeInMilliseconds;
      aParam := Form1.RESTRequest1.Params.AddItem;
      aParam.ContentType:=ctapplication_x_www_form_urlencoded;
      aParam.Kind := pkGETorPOST; 
      aParam.name := 'timestamp';
      aParam.Value := TimeStamp;

      PRE_SIGN := format('%s?timestamp=%s', [Form1.RESTClient1.BaseURL,
        TimeStamp]);
      SIGNATURE := SHA512DigestToHexW(CalcHMAC_SHA512(Form1.SECRET_Binance,
        PRE_SIGN));
      aParam := Form1.RESTRequest1.Params.AddItem;
      aParam.ContentType:=ctapplication_x_www_form_urlencoded;
      aParam.Kind := pkHTTPHEADER;
      aParam.name := 'signature';
      aParam.Value := SIGNATURE;

      Form1.RESTRequest1.Execute;

**Comment by 2pd** [comment]
Please open a topic at  https://dev.binance.vision/ for API concerns.   I don't think this issue is related to the repo.

However `timestamp=%s` is the only string required to sign for this endpoint. :)

**Comment by 2pd** [comment]
@surinpeter  how is going with this issue, can we close it?

**Comment by surinpeter** [comment]
Thank You, we can close it.
